/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as AdminFarmersRouteImport } from './routes/admin_.farmers'
import { Route as AdminListingsRouteImport } from './routes/admin_.listings'
import { Route as EquipmentIdRouteImport } from './routes/equipment_.$id'
import { Route as EquipmentNewRouteImport } from './routes/equipment_.new'
import { Route as AdminFarmersIdRouteImport } from './routes/admin_.farmers_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SchemesScopeIdRouteImport } from './routes/schemes_.$scope.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFarmersRoute = AdminFarmersRouteImport.update({
  id: '/admin_/farmers',
  path: '/admin/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/admin_/listings',
  path: '/admin/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdRoute = EquipmentIdRouteImport.update({
  id: '/equipment_/$id',
  path: '/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentNewRoute = EquipmentNewRouteImport.update({
  id: '/equipment_/new',
  path: '/equipment/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFarmersIdRoute = AdminFarmersIdRouteImport.update({
  id: '/admin_/farmers_/$id',
  path: '/admin/farmers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesScopeIdRoute = SchemesScopeIdRouteImport.update({
  id: '/schemes_/$scope/$id',
  path: '/schemes/$scope/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/weather': typeof WeatherRoute
  '/admin/farmers': typeof AdminFarmersRoute
  '/admin/listings': typeof AdminListingsRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/admin/farmers/$id': typeof AdminFarmersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/schemes/$scope/$id': typeof SchemesScopeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/weather': typeof WeatherRoute
  '/admin/farmers': typeof AdminFarmersRoute
  '/admin/listings': typeof AdminListingsRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/admin/farmers/$id': typeof AdminFarmersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/schemes/$scope/$id': typeof SchemesScopeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/weather': typeof WeatherRoute
  '/admin_/farmers': typeof AdminFarmersRoute
  '/admin_/listings': typeof AdminListingsRoute
  '/equipment_/$id': typeof EquipmentIdRoute
  '/equipment_/new': typeof EquipmentNewRoute
  '/admin_/farmers_/$id': typeof AdminFarmersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/schemes_/$scope/$id': typeof SchemesScopeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/equipment'
    | '/login'
    | '/market'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/schemes'
    | '/settings'
    | '/support'
    | '/weather'
    | '/admin/farmers'
    | '/admin/listings'
    | '/equipment/$id'
    | '/equipment/new'
    | '/admin/farmers/$id'
    | '/api/auth/$'
    | '/schemes/$scope/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/equipment'
    | '/login'
    | '/market'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/schemes'
    | '/settings'
    | '/support'
    | '/weather'
    | '/admin/farmers'
    | '/admin/listings'
    | '/equipment/$id'
    | '/equipment/new'
    | '/admin/farmers/$id'
    | '/api/auth/$'
    | '/schemes/$scope/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/equipment'
    | '/login'
    | '/market'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/schemes'
    | '/settings'
    | '/support'
    | '/weather'
    | '/admin_/farmers'
    | '/admin_/listings'
    | '/equipment_/$id'
    | '/equipment_/new'
    | '/admin_/farmers_/$id'
    | '/api/auth/$'
    | '/schemes_/$scope/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  EquipmentRoute: typeof EquipmentRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SchemesRoute: typeof SchemesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  WeatherRoute: typeof WeatherRoute
  AdminFarmersRoute: typeof AdminFarmersRoute
  AdminListingsRoute: typeof AdminListingsRoute
  EquipmentIdRoute: typeof EquipmentIdRoute
  EquipmentNewRoute: typeof EquipmentNewRoute
  AdminFarmersIdRoute: typeof AdminFarmersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SchemesScopeIdRoute: typeof SchemesScopeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/farmers': {
      id: '/admin_/farmers'
      path: '/admin/farmers'
      fullPath: '/admin/farmers'
      preLoaderRoute: typeof AdminFarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/listings': {
      id: '/admin_/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment_/$id': {
      id: '/equipment_/$id'
      path: '/equipment/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof EquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment_/new': {
      id: '/equipment_/new'
      path: '/equipment/new'
      fullPath: '/equipment/new'
      preLoaderRoute: typeof EquipmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/farmers_/$id': {
      id: '/admin_/farmers_/$id'
      path: '/admin/farmers/$id'
      fullPath: '/admin/farmers/$id'
      preLoaderRoute: typeof AdminFarmersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes_/$scope/$id': {
      id: '/schemes_/$scope/$id'
      path: '/schemes/$scope/$id'
      fullPath: '/schemes/$scope/$id'
      preLoaderRoute: typeof SchemesScopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  EquipmentRoute: EquipmentRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SchemesRoute: SchemesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  WeatherRoute: WeatherRoute,
  AdminFarmersRoute: AdminFarmersRoute,
  AdminListingsRoute: AdminListingsRoute,
  EquipmentIdRoute: EquipmentIdRoute,
  EquipmentNewRoute: EquipmentNewRoute,
  AdminFarmersIdRoute: AdminFarmersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SchemesScopeIdRoute: SchemesScopeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
